#!/bin/sh

set -eu

usage() {
  cat <<'EOF'
Usage: ./scripts/setup-self-host.sh [--force] [APP_HOST [LIVEKIT_HOST]]

Generate production environment files for a self-hosted Concord instance.
APP_HOST serves the zero-install web client and token API.
If LIVEKIT_HOST is omitted, APP_HOST is used for both services.

Examples:
  ./scripts/setup-self-host.sh concord.example.com
  ./scripts/setup-self-host.sh concord.example.com livekit.example.com
EOF
}

validate_hostname() (
  hostname=$1

  case "$hostname" in
    '' | .* | *. | *..* | *[!A-Za-z0-9.-]*) exit 1 ;;
  esac

  old_ifs=$IFS
  IFS=.
  set -- $hostname
  IFS=$old_ifs

  for label do
    case "$label" in
      '' | -* | *-) exit 1 ;;
    esac
  done
)

force=false
api_host=''
livekit_host=''

while [ "$#" -gt 0 ]; do
  case "$1" in
    --force)
      force=true
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    -*)
      printf 'Unknown option: %s\n\n' "$1" >&2
      usage >&2
      exit 1
      ;;
    *)
      if [ -z "$api_host" ]; then
        api_host=$1
      elif [ -z "$livekit_host" ]; then
        livekit_host=$1
      else
        printf 'Too many hostnames provided.\n\n' >&2
        usage >&2
        exit 1
      fi
      ;;
  esac
  shift
done

if [ -z "$api_host" ]; then
  printf 'Public app hostname (for example, concord.example.com): '
  IFS= read -r api_host
fi

if ! validate_hostname "$api_host"; then
  printf 'Invalid app hostname: %s\n' "$api_host" >&2
  exit 1
fi

if [ -z "$livekit_host" ]; then
  livekit_host=$api_host
fi

if ! validate_hostname "$livekit_host"; then
  printf 'Invalid LiveKit hostname: %s\n' "$livekit_host" >&2
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  printf 'openssl is required to generate secure LiveKit credentials.\n' >&2
  exit 1
fi

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
project_root=$(CDPATH= cd -- "$script_dir/.." && pwd)
server_env="$project_root/.env"
desktop_env="$project_root/apps/desktop/.env.local"

if [ "$force" = false ] && { [ -e "$server_env" ] || [ -e "$desktop_env" ]; }; then
  printf 'Refusing to overwrite an existing environment file.\n' >&2
  [ -e "$server_env" ] && printf '  %s\n' "$server_env" >&2
  [ -e "$desktop_env" ] && printf '  %s\n' "$desktop_env" >&2
  printf 'Run again with --force to replace both files.\n' >&2
  exit 1
fi

umask 077
api_key=$(openssl rand -hex 16)
api_secret=$(openssl rand -hex 32)
server_tmp="$server_env.tmp.$$"
desktop_tmp="$desktop_env.tmp.$$"

cleanup() {
  rm -f "$server_tmp" "$desktop_tmp"
}
trap cleanup EXIT HUP INT TERM

cat >"$server_tmp" <<EOF
# Generated by scripts/setup-self-host.sh. Keep this file private.
LIVEKIT_URL=wss://$livekit_host
LIVEKIT_API_KEY=$api_key
LIVEKIT_API_SECRET=$api_secret
PORT=3001
ALLOWED_ORIGINS=https://$api_host
PUBLIC_APP_URL=https://$api_host
PUBLIC_TOKEN_SERVER_URL=https://$api_host
EOF

cat >"$desktop_tmp" <<EOF
# Rebuild the desktop app after changing this URL.
VITE_TOKEN_SERVER_URL=https://$api_host
VITE_WEB_APP_URL=https://$api_host
EOF

mv "$server_tmp" "$server_env"
mv "$desktop_tmp" "$desktop_env"
trap - EXIT HUP INT TERM

printf 'Generated:\n'
printf '  %s\n' "$server_env"
printf '  %s\n' "$desktop_env"
printf '\nApp URL:     https://%s\n' "$api_host"
printf 'LiveKit URL: wss://%s\n' "$livekit_host"
printf '\nNext: configure LiveKit networking, start the production Compose stack, and rebuild the desktop app with pnpm make.\n'
